### ISSUE TITLE
[BUG]: Error in evaluation in predictor.py

### ISSUE THREAD

**Issue by KatherineJames** [LCAS/aoc_fruit_detector#27]
### Description of the bug

I am aiming to run the evaluation of the model's performance on the dataset. In predictor.py, I call the call_predictor() function, however my first issue is that the line with ```yield``` causes it to do nothing. If I remove this line then I get an error as below. I believe that this code has got out of sync with the rest of the repo on the main branch due to integration with ROS.

Traceback (most recent call last):
  File "/home/ros/fruit_detector_ws/src/aoc_fruit_detector/scripts/detectron_predictor/detectron_predictor.py", line 182, in get_predictions_image
    os.makedirs(pred_image_dir)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: './data/strawberry_dataset/test/sample_118.png/predicted_images'

### Steps To Reproduce

I am running this from ~/fruit_detector_ws/src/aoc_fruit_detector/scripts: python predictor.py

This is my non_ros_params file:
```
datasets:
  train_dataset_name: 'aoc_train_dataset'
  test_dataset_name: 'aoc_test_dataset'
  validation_dataset_name: 'aoc_validation_dataset'
  dataset_train_annotation_url: '[https://lncn.ac/aocanntrain'](https://lncn.ac/aocanntrain%27)
  dataset_train_images_url: '[https://lncn.ac/aocdatatrain'](https://lncn.ac/aocdatatrain%27)
  dataset_test_annotation_url: '[https://lncn.ac/aocanntest'](https://lncn.ac/aocanntest%27)
  dataset_test_images_url: '[https://lncn.ac/aocdatatest'](https://lncn.ac/aocdatatest%27)
files:
  # pretrained model used as a training base model, if set as empty, the config file will use imagenet trained model as base.
  pretrained_model_file: ''
  # model_file: './model/aoc_tomato_ripeness_151_40k.pth'
  model_file: './model/aoc_strawberry_class_fruit.pth' #'./model/aoc_model.pth'
  config_file: 'COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml'
  test_metadata_catalog_file: './data/dataset_catalogs/test_metadata_catalog.pkl'
  train_dataset_catalog_file: './data/dataset_catalogs/tom_train_dataset_catalog.pkl'
  train_annotation_file: './data/strawberry_dataset/train/annotations/ripeness_class_annotations.json'
  test_annotation_file: './data/strawberry_dataset/test/annotations/test_annotations.json'
  validation_annotation_file: './data/strawberry_dataset/val/annotations/ripeness_class_annotations.json'
  model_url: '[https://lncn.ac/aocmodel'](https://lncn.ac/aocmodel%27)
  meta_catalog_url: '[https://lncn.ac/aocmeta'](https://lncn.ac/aocmeta%27)
  train_catalog_url: '[https://lncn.ac/aoccat'](https://lncn.ac/aoccat%27)
directories:
  train_image_dir: './data/strawberry_dataset/train/'
  test_image_dir: './data/strawberry_dataset/test/' #'./data/strawberry_dataset/test/'
  validation_image_dir: './data/strawberry_dataset/val/'
  training_output_dir: './data/training_output/'
  prediction_output_dir: './data/prediction_output/test_images/'
  prediction_json_dir: './data/annotations/predicted/'
training:
  epochs: 40000
  number_of_classes: 1
  optimizer: 'SGD'
  learning_rate: 0.0025
settings:
  download_assets: false # if assets such as model and datasets should be downloaded
  rename_pred_images: false #rename the predicted images in img_000001.png like format
  segm_masks: true
  bbox: true
  show_orientation: false
  fruit_type: 'strawberry' # currently supported for "strawberry" or "tomato"
  validation_period: 500 # Smaller validation will increase training time. The value is set to have 100 validation during training
```
